from django.db import models
from django.conf import settings

class ChatMessage(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL,on_delete=models.CASCADE,null=True,blank=True,)
    session_id = models.CharField(max_length=100,db_index=True,)
    user_message = models.TextField(help_text="Message sent by the user")
    bot_response = models.TextField(help_text="Reply generated by WanderBot")
    created_at = models.DateTimeField(auto_now_add=True)

    class Meta:
        ordering = ['-created_at']

    def __str__(self):
        preview = self.user_message[:60]
        return f"[{self.session_id[:8]}] {preview}"