# Generated by Django 5.2.7 on 2025-11-08 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='last_otp_sent_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
