# Generated by Django 5.2.6 on 2025-10-15 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_user_otp_attempts_user_otp_locked_until_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='otp_type',
            field=models.CharField(blank=True, choices=[('registration', 'Registration'), ('password_reset', 'Password Reset')], max_length=20, null=True),
        ),
    ]
