# Generated by Django 5.2.6 on 2025-10-15 04:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_user_otp_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='name',
        ),
        migrations.RemoveField(
            model_name='user',
            name='phone_number',
        ),
        migrations.RemoveField(
            model_name='user',
            name='terms_accepted',
        ),
    ]
