# Generated by Django 5.2.6 on 2025-11-10 09:17

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ItenaryMaker', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dayplan',
            name='activities',
        ),
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.CharField(max_length=500)),
                ('location', models.CharField(max_length=200)),
                ('time', models.IntegerField(choices=[(1, 'Morning'), (2, 'Afternoon'), (3, 'Evening')], default='morning', max_length=10)),
                ('timings', models.TimeField()),
                ('budget_alloted', models.FloatField(validators=[django.core.validators.MinValueValidator(0)])),
                ('category', models.CharField(max_length=400)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('day_plans', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Activity', to='ItenaryMaker.dayplan')),
            ],
            options={
                'ordering': ['time'],
                'unique_together': {('day_plans', 'title')},
            },
        ),
    ]
