# Generated by Django 5.2.6 on 2025-11-11 06:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ItenaryMaker', '0002_remove_dayplan_activities_activity'),
    ]

    operations = [
        migrations.RenameField(
            model_name='activity',
            old_name='budget_alloted',
            new_name='cost',
        ),
        migrations.AlterField(
            model_name='activity',
            name='day_plans',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='ItenaryMaker.dayplan'),
        ),
        migrations.AlterField(
            model_name='activity',
            name='time',
            field=models.CharField(choices=[('morning', 'Morning'), ('afternoon', 'Afternoon'), ('evening', 'Evening')], default='morning', max_length=10),
        ),
        migrations.AlterField(
            model_name='activity',
            name='timings',
            field=models.CharField(),
        ),
    ]
