# Generated by Django 5.2.6 on 2025-11-11 07:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ItenaryMaker', '0003_rename_budget_alloted_activity_cost_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='activity',
            options={},
        ),
    ]
