# Generated by Django 5.2.6 on 2025-11-01 04:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0002_alter_post_loc_rating'),
        ('community', '0002_alter_post_options_post_updated_at'),
    ]

    operations = [
    ]
