# Generated by Django 5.2.6 on 2025-10-28 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WeatherCache',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(max_length=100, unique=True)),
                ('temperature', models.FloatField()),
                ('wind', models.FloatField()),
                ('chance_of_rain', models.IntegerField()),
            ],
        ),
    ]
