# Generated by Django 5.2.7 on 2025-11-12 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WeatherCache',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(max_length=100, unique=True)),
                ('temperature', models.FloatField()),
                ('wind', models.FloatField()),
                ('chance_of_rain', models.IntegerField()),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Weather Cache',
                'verbose_name_plural': 'Weather Caches',
                'ordering': ['-updated_at'],
            },
        ),
    ]
