# Generated by Django 5.2.7 on 2025-10-31 10:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HomePage', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='weathercache',
            options={'ordering': ['-updated_at'], 'verbose_name': 'Weather Cache', 'verbose_name_plural': 'Weather Caches'},
        ),
        migrations.AddField(
            model_name='weathercache',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2025, 10, 31, 10, 44, 29, 116120, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='weathercache',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
