<<<<<<< HEAD
# Generated by Django 5.2.7 on 2025-11-01 08:08
=======
# Generated by Django 5.2.6 on 2025-11-01 07:14
>>>>>>> 585dbdbd44e1c38b8a308644c9a334357890f42e

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tripname', models.CharField(max_length=100)),
                ('current_loc', models.CharField(max_length=200)),
                ('destination', models.CharField(max_length=200)),
                ('trending', models.BooleanField(default=False)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('days', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(7)])),
                ('trip_type', models.CharField(choices=[('group', 'Group Trip'), ('solo', 'Solo Trip')], max_length=20)),
                ('trip_preferences', models.CharField(choices=[('adventure', 'Adventure'), ('relaxation', 'Relaxation'), ('spiritual', 'Spiritual')], max_length=20)),
                ('budget', models.FloatField(validators=[django.core.validators.MinValueValidator(2000)])),
                ('itinerary_data', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trips', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
