# Generated by Django 5.2.6 on 2025-11-01 07:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ItenaryMaker', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='trip',
            old_name='itinerary_data',
            new_name='Itenary_data',
        ),
    ]
