# Generated by Django 5.2.6 on 2025-11-03 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ItenaryMaker', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='Itenary_json',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
