# Generated by Django 5.2.7 on 2025-11-12 14:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(default='', max_length=100)),
                ('lname', models.CharField(default='', max_length=100)),
                ('phone_number', models.CharField(max_length=17, unique=True)),
                ('is_phone_verified', models.BooleanField(default=False)),
                ('date', models.DateField(default='2000-01-01')),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other')], default='other', max_length=10)),
                ('bio', models.TextField(default='', max_length=500)),
                ('profile_pic', models.ImageField(blank=True, null=True, upload_to='profile_pics/')),
                ('bgroup', models.CharField(choices=[('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('AB+', 'AB+'), ('AB-', 'AB-'), ('O+', 'O+'), ('O-', 'O-')], default='O+', max_length=3)),
                ('allergies', models.TextField(blank=True, default='', max_length=200)),
                ('medical', models.TextField(blank=True, default='', max_length=500)),
                ('ename', models.CharField(default='', max_length=100)),
                ('enumber', models.CharField(default='', max_length=17)),
                ('erelation', models.CharField(choices=[('Spouse', 'Spouse'), ('Parent', 'Parent'), ('Friend', 'Friend'), ('Sibling', 'Sibling')], default='Parent', max_length=20)),
                ('prefrence', models.CharField(choices=[('Adventure', 'Adventure'), ('Relaxation', 'Relaxation'), ('Nature', 'Nature'), ('Explore', 'Explore'), ('Spiritual', 'Spiritual'), ('Historic', 'Historic')], default='Relaxation', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('otp', models.CharField(blank=True, max_length=255, null=True)),
                ('otp_exp', models.DateTimeField(blank=True, null=True)),
                ('otp_attempts', models.IntegerField(default=0)),
                ('otp_locked_until', models.DateTimeField(blank=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Profile',
                'verbose_name_plural': 'User Profiles',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['phone_number'], name='personal_pr_phone_n_daf837_idx'), models.Index(fields=['is_phone_verified'], name='personal_pr_is_phon_d88cf6_idx')],
            },
        ),
    ]
