# Generated by Django 5.2.7 on 2025-10-28 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personal', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profile',
            options={'ordering': ['-created_at'], 'verbose_name': 'User Profile', 'verbose_name_plural': 'User Profiles'},
        ),
        migrations.AlterField(
            model_name='profile',
            name='allergies',
            field=models.TextField(blank=True, default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='profile',
            name='bgroup',
            field=models.CharField(choices=[('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('AB+', 'AB+'), ('AB-', 'AB-'), ('O+', 'O+'), ('O-', 'O-')], default='O+', max_length=3),
        ),
        migrations.AlterField(
            model_name='profile',
            name='bio',
            field=models.TextField(default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='profile',
            name='date',
            field=models.DateField(default='2000-01-01'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='ename',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='profile',
            name='enumber',
            field=models.CharField(default='', max_length=17),
        ),
        migrations.AlterField(
            model_name='profile',
            name='erelation',
            field=models.CharField(choices=[('Spouse', 'Spouse'), ('Parent', 'Parent'), ('Friend', 'Friend'), ('Sibling', 'Sibling')], default='Parent', max_length=20),
        ),
        migrations.AlterField(
            model_name='profile',
            name='fname',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='profile',
            name='gender',
            field=models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other')], default='other', max_length=10),
        ),
        migrations.AlterField(
            model_name='profile',
            name='lname',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='profile',
            name='medical',
            field=models.TextField(blank=True, default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='profile',
            name='prefrence',
            field=models.CharField(choices=[('Adventure', 'Adventure'), ('Relaxation', 'Relaxation'), ('Nature', 'Nature'), ('Explore', 'Explore'), ('Spiritual', 'Spiritual'), ('Historic', 'Historic')], default='Relaxation', max_length=50),
        ),
    ]
