# Generated by Django 5.2.7 on 2025-10-31 15:47

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('expense', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='budget',
            old_name='total_budget',
            new_name='total',
        ),
        migrations.RenameField(
            model_name='expensecategory',
            old_name='allocated_amount',
            new_name='allocated',
        ),
        migrations.RenameField(
            model_name='expensecategory',
            old_name='category_type',
            new_name='category',
        ),
        migrations.AlterUniqueTogether(
            name='expensecategory',
            unique_together={('user', 'category')},
        ),
    ]
