# Generated by Django 5.2.7 on 2025-11-03 17:19

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TrendingPlace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('main', models.ImageField(upload_to='places/')),
            ],
        ),
        migrations.CreateModel(
            name='FunFact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slide', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)])),
                ('title', models.CharField(max_length=100)),
                ('desc', models.TextField(max_length=1500)),
                ('photo', models.ImageField(upload_to='funfacts/')),
                ('place', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fun_facts', to='trending.trendingplace')),
            ],
            options={
                'ordering': ['slide'],
                'unique_together': {('place', 'slide')},
            },
        ),
    ]
