# Generated by Django 5.2.7 on 2025-11-03 16:30

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trending', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='funfact',
            name='desc',
            field=models.TextField(max_length=1500),
        ),
        migrations.AlterField(
            model_name='funfact',
            name='slide',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)]),
        ),
        migrations.AlterField(
            model_name='funfact',
            name='title',
            field=models.CharField(max_length=100),
        ),
    ]
