# Generated by Django 6.0.4 on 2026-05-21 10:24

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account', '0002_usersocialaccount'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Itinerary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(choices=[('ai', 'AI Generated'), ('manual', 'Manual')], default='ai', max_length=10)),
                ('last_generated_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Itinerary',
            },
        ),
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('place_id', models.CharField(db_index=True, max_length=200, unique=True)),
                ('name', models.CharField(max_length=300)),
                ('address', models.CharField(blank=True, max_length=500)),
                ('lat', models.FloatField()),
                ('lng', models.FloatField()),
                ('phone', models.CharField(blank=True, max_length=50)),
                ('website', models.URLField(blank=True)),
                ('rating', models.FloatField(blank=True, null=True)),
                ('photo_reference', models.CharField(blank=True, max_length=600)),
                ('photo_url', models.URLField(blank=True, max_length=1000)),
                ('types', models.JSONField(default=list)),
                ('opening_hours', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Place',
            },
        ),
        migrations.CreateModel(
            name='UserBudget',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='budget', serialize=False, to=settings.AUTH_USER_MODEL)),
                ('total', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(0)])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'User Budget',
            },
        ),
        migrations.CreateModel(
            name='DayPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_number', models.IntegerField()),
                ('title', models.CharField(max_length=200)),
                ('date', models.DateField(blank=True, null=True)),
                ('tips', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('itinerary', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='day_plans', to='Itinerary.itinerary')),
            ],
            options={
                'verbose_name': 'Day Plan',
                'ordering': ['day_number'],
                'unique_together': {('itinerary', 'day_number')},
            },
        ),
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tripname', models.CharField(max_length=100)),
                ('current_loc', models.CharField(max_length=200)),
                ('destination', models.CharField(max_length=200)),
                ('destination_lat', models.FloatField(blank=True, null=True)),
                ('destination_lng', models.FloatField(blank=True, null=True)),
                ('trending', models.BooleanField(default=False)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('days', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(30)])),
                ('trip_type', models.CharField(choices=[('solo', 'Solo'), ('group', 'Group')], max_length=20)),
                ('trip_preferences', models.CharField(choices=[('relaxation', 'Relaxation'), ('adventure', 'Adventure'), ('spiritual', 'Spiritual'), ('cultural', 'Cultural'), ('food', 'Food & Culinary'), ('nature', 'Nature')], max_length=20)),
                ('total_budget', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(0)])),
                ('budget_split_method', models.CharField(choices=[('ai', 'AI Generated'), ('manual', 'Manually Set')], default='ai', max_length=10)),
                ('language', models.CharField(default='en', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trips', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Trip',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ItineraryExport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('format', models.CharField(choices=[('pdf', 'PDF'), ('docx', 'Word Document')], max_length=10)),
                ('file', models.FileField(upload_to='exports/%Y/%m/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('trip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exports', to='Itinerary.trip')),
            ],
            options={
                'verbose_name': 'Itinerary Export',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='itinerary',
            name='trip',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='itinerary', to='Itinerary.trip'),
        ),
        migrations.CreateModel(
            name='TripBudgetCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('accommodation', 'Accommodation'), ('food', 'Food & Dining'), ('transport', 'Transport'), ('activities', 'Activities & Sightseeing'), ('shopping', 'Shopping'), ('emergency', 'Emergency'), ('other', 'Other')], max_length=20)),
                ('allocated', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(0)])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('trip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='budget_categories', to='Itinerary.trip')),
            ],
            options={
                'verbose_name': 'Trip Budget Category',
                'ordering': ['category'],
                'unique_together': {('trip', 'category')},
            },
        ),
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('time', models.CharField(choices=[('morning', 'Morning'), ('afternoon', 'Afternoon'), ('evening', 'Evening'), ('night', 'Night')], max_length=10)),
                ('start_time', models.TimeField(blank=True, null=True)),
                ('end_time', models.TimeField(blank=True, null=True)),
                ('category', models.CharField(choices=[('sightseeing', 'Sightseeing'), ('dining', 'Dining'), ('shopping', 'Shopping'), ('transportation', 'Transportation'), ('adventure', 'Adventure'), ('relaxation', 'Relaxation'), ('accommodation', 'Accommodation'), ('emergency', 'Emergency')], max_length=20)),
                ('location_name', models.CharField(blank=True, max_length=300)),
                ('estimated_cost', models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('short_description', models.TextField(blank=True)),
                ('dos_and_donts', models.TextField(blank=True)),
                ('emergency_contacts', models.JSONField(default=list)),
                ('distance_km', models.FloatField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('day_plans', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='Itinerary.dayplan')),
                ('place', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activities', to='Itinerary.place')),
                ('budget_category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activities', to='Itinerary.tripbudgetcategory')),
            ],
            options={
                'verbose_name': 'Activity',
            },
        ),
    ]
