# Generated by Django 6.0.4 on 2026-05-23 08:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Itinerary', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserBudget',
        ),
    ]
