# Generated by Django 6.0.4 on 2026-04-14 15:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(max_length=100, verbose_name='First name')),
                ('lname', models.CharField(blank=True, default='', max_length=100, verbose_name='Last name')),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other')], max_length=10, verbose_name='Gender')),
                ('date_of_birth', models.DateField(help_text='Must be between 13 and 110 years old.', verbose_name='Date of birth')),
                ('bio', models.TextField(blank=True, default='', max_length=500, verbose_name='Bio')),
                ('profile_pic', models.CharField(blank=True, default='', max_length=500, verbose_name='Profile picture URL')),
                ('blood_group', models.CharField(choices=[('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('AB+', 'AB+'), ('AB-', 'AB-'), ('O+', 'O+'), ('O-', 'O-')], max_length=3, verbose_name='Blood group')),
                ('allergies', models.TextField(max_length=300, verbose_name='Allergies')),
                ('medical', models.TextField(max_length=500, verbose_name='Medical conditions')),
                ('preference', models.CharField(choices=[('relaxed', 'Relaxed'), ('adventurous', 'Adventurous'), ('nature', 'Nature'), ('cultural', 'Cultural'), ('spiritual', 'Spiritual'), ('historic', 'Historic')], max_length=20, verbose_name='Trip preference')),
                ('preferred_destinations', models.JSONField(default=list, verbose_name='Preferred destinations')),
                ('language', models.CharField(choices=[('en', 'English'), ('hi', 'Hindi'), ('ar', 'Arabic'), ('fr', 'French'), ('es', 'Spanish')], default='en', max_length=2, verbose_name='Language preference')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Profile',
                'verbose_name_plural': 'Profiles',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='EmergencyContact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Contact name')),
                ('phone_number', models.CharField(help_text='International format e.g. +911234567890.', max_length=17, verbose_name='Phone number')),
                ('email', models.EmailField(help_text='Emergency alert emails are sent here.', max_length=254, verbose_name='Email address')),
                ('relation', models.CharField(choices=[('Spouse', 'Spouse'), ('Parent', 'Parent'), ('Friend', 'Friend'), ('Sibling', 'Sibling'), ('Other', 'Other')], max_length=10, verbose_name='Relation')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emergency_contacts', to='personal.profile')),
            ],
            options={
                'verbose_name': 'Emergency Contact',
                'verbose_name_plural': 'Emergency Contacts',
                'ordering': ['created_at'],
            },
        ),
    ]
